### ISSUE TITLE
[S1-PB2] Membuat Halaman Login

### ISSUE THREAD

**Issue by naovalm** [SI-RPL-2023/SI4403_KEL236_DuniaTani#2]
![Image](https://user-images.githubusercontent.com/115627442/228871720-757ab598-824d-4d4e-84bb-2a9362debf8a.png)

 Halaman login ini harus memungkinkan pengguna untuk masuk ke dalam akun mereka di situs web dan mengakses konten premium seperti artikel, video tutorial, dan lainnya. Selain itu, halaman login juga harus memastikan keamanan dan privasi data pengguna, serta memungkinkan pengguna keluar dari akun mereka dengan mudah.

**Comment by naovalm** [comment]
Analyst bisa melakukan pull, lalu periksa [S1-PB3] @StefanusRicardoM

**Comment by StefanusRicardoM** [comment]
front end sudah berjalan 👍

**Comment by StefanusRicardoM** [comment]
tinggal nambahin backend yak

**Comment by naovalm** [comment]
silahkan dicek lagi @StefanusRicardoM

**Comment by StefanusRicardoM** [comment]
login juga dah bisa pake akun yang dah di regis, consider it done
