### ISSUE TITLE
[S1-PB3] Membuat Halaman Landing Page

### ISSUE THREAD

**Issue by naovalm** [SI-RPL-2023/SI4403_KEL236_DuniaTani#3]
![Image](https://user-images.githubusercontent.com/115627442/228872681-9a1bd514-2a6a-4466-a787-c6ff7a0cd132.png)

Halaman landing page ini harus memperkenalkan situs web dan kontennya dengan jelas dan menarik perhatian pengunjung. Selain itu, halaman ini juga harus dirancang untuk meningkatkan konversi pengunjung menjadi pengguna aktif dengan menampilkan fitur dan manfaat situs web dengan jelas.

**Comment by Slky00** [comment]
OTW Buat homepage

**Comment by naovalm** [comment]
Analyst bisa melakukan pull, lalu periksa [S1-PB3] @StefanusRicardoM

**Comment by StefanusRicardoM** [comment]
landing page sudah bisa berjalan
