### ISSUE TITLE
[S1-PB4] Membuat Halaman Halaman Event

### ISSUE THREAD

**Issue by naovalm** [SI-RPL-2023/SI4403_KEL236_DuniaTani#4]
![Image](https://user-images.githubusercontent.com/115627442/228873925-27de6511-5d99-4908-893d-d8182e7c0d34.png)

Halaman event ini harus memberikan informasi tentang acara yang akan datang, seperti tanggal, waktu, lokasi, deskripsi, dan juga memungkinkan pengguna untuk mendaftar atau membeli tiket untuk acara tersebut.

**Comment by Slky00** [comment]
need review kakak

**Comment by naovalm** [comment]
Analyst bisa melakukan pull, lalu periksa [S1-PB4] @StefanusRicardoM

**Comment by StefanusRicardoM** [comment]
mantab deck halaman event dah jalan

**Comment by StefanusRicardoM** [comment]
ok sudah bener yah
